spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/WebMusic?useSSL=false&serverTimezone=UTC
        username: root
        password: "775028"

    servlet:
        multipart:
            enabled: true #是否启用http上传处理
            max-file-size: 60MB #设置单个文件最大长度
            max-request-size: 100MB #最大请求文件的大小
    mvc:
        #本地静态资源访问url前缀
        static-path-pattern: /**

        #本地静态资源
        static-locations: file:${web.upload-path}
        #本地静态资源配置映射目录，应该是下面的方法
    devtools:
        restart:
            additional-paths: src/main/resource/static
    web:
        resources:
            static-locations[0]:
                file:src/main/resources/static/
            static-locations[1]:
                classpath:/static/
    mail:
        host:
            smtp.qq.com
        username:
            1262229357@qq.com
        password:
            sukpkmlqdjmqjjff
        from:
            lian.wk04201@foxmail.com
        default-encoding:
            utf-8
        properties:
            mail:
                transport:
                    protocol: smtp
                smtp:
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                    port: ${spring.mail.port}
                    auth: true
                    starttls:
                        enable: true
                        required: true
        port:
            465
web:
    #本地磁盘存储路径,注意不要最后目录的/
    upload-path: /Users/acaibird/Documents/CodeExperimentSpace/Java/spring/src/main/resources/static


server:
    port: 8080
    servlet:
        session:
            timeout: 1800

logging:
    config: src/main/resources/lombok-springboot-log.xml

musicfileDir: "/Users/acaibird/Documents/CodeExper  imentSpace/Java/spring/src/main/resources/static/music/"